version: "3.8"

services:

  app:
    image: evidence-service:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite-blob --blobHost 0.0.0.0 --location /data"
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data
    networks:
      - backend
    deploy:
      replicas: 1

volumes:
  azurite_data:

networks:
  backend:
