[project]
name = "evidence-service"
version = "0.1.0"
description = "Microservice for storing evidences using Azurite"
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn",
    "python-dotenv",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "httpx"
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
include = ["app*"]
exclude = ["docker*", "tests*"]
